GET http://localhost:3000/3
###
GET http://localhost:3000/4
###
POST http://localhost:3000/number/1
###
POST http://localhost:3000/number/2
###
POST http://localhost:3000/number/5
###
DELETE  http://localhost:3000/number/1
###
DELETE  http://localhost:3000/number/2
###
PUT  http://localhost:3000/number/5/10
###
POST http://localhost:3000/countfields
content-type: application/json

{
    "a": "1",
    "b": "2",
    "c": "3"
}
###
POST http://localhost:3000/countfields
content-type: application/json

{
    "a": "1",
    "b": "2",
    "c": "3",
    "d": "4"
}